package config;

public class Const {
    public static final String ORDER_COUPONE = "orderCoupone";
    public static final String ORDER_DAY = "day";
    public static final String ORDER_TIME = "time";
    public static final String ORDER_USER_ID = "user_id";
    public static final String ORDER_DOCTOR_ID = "doctor_id";
    public static final String ORDER_NUMBER_TICKET = "numberTicket";
    public static final String SCHEDULE_NAME_DAY = "nameDay";
    public static final String SCHEDULE_COUNT_TICKET = "countTicket";
    public static final String SCHEDULE_DOCTOR_ID = "doctor_id";
    public static final String USERS_ID = "id";
    public static final String ORDER_PAID_SERVICE = "order_paid_service";
    public static final String USERS_NAME = "name";
    public static final String USERS_SURNAME = "surname";
    public static final String USERS_EMAIL = "email";
    public static final String USERS_PASSWORD = "password";
    public static final String USERS_TABLE = "users";
    public static final String DOCTORS_TABLE = "doctors";
    public static final String SCHEDULE_TABLE = "schedule";
    public static final String USERS_ROLE_ID = "role_id";
    public static final String USERS_SPECIALTY = "specialty";
    public static final String SERVICES_TABLE = "services";
    public static final String SERVICES_PRICE = "price";
    public static final String HOST = "127.0.0.1";
    public static final int PORT = 2525;
    public static final int BLOCK_USERS = -1;
    public static final int UNLOCK_USERS = 2;
    public static final String PAID_TABLE = "paidServices";
    public static final String PAID_SERVICES = "paidServices";
    public static final String SERVICES_ID = "services_id";
    static final String PATH_ORDER_CONFIRM = "../fxml/clientFXML/orderConfirmService.fxml";
    static final String PATH_USERS_VIEW = "../fxml/adminFXML/viewUsers.fxml";
    static final String PATH_ADD_PAID_SERVICES = "../fxml/adminFXML/addPaidServices.fxml";
    static final String PATH_PAID_SERVICES = "../fxml/clientFXML/paidServicesView.fxml";
    static final String PATH_INFORMATION_VIEW = "../fxml/clientFXML/informationView.fxml";
    static final String PATH_ORDER_VIEW = "../fxml/clientFXML/orderView.fxml";
    static final String PATH_MAIN_VIEW = "../fxml/mainFXML/mainView.fxml";
    static final String PATH_MAIN_CSS = "../css/main.css";
    static final String PATH_AUTHENTICATION = "../fxml/mainFXML/authentication.fxml";
    static final String PATH_REGISTRATION = "../fxml/mainFXML/registration.fxml";
    static final String PATH_CLIENT_VIEW = "../fxml/clientFXML/clientView.fxml";
    static final String PATH_DOCTOR_STAGE = "../fxml/doctorFXML/doctorView.fxml";
    static final String PATH_ADMIN_STAGE = "../fxml/adminFXML/adminView.fxml";
    static final String PATH_ADD_DOCTOR = "../fxml/adminFXML/editDoctorView.fxml";
}
